import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import Header from './Header'
import './globals.css'

// Fonts
const inter = Inter({ subsets: ['latin'] })
const gerbera = localFont({
  src: './Gerbera-Light.otf',
  variable: '--font-gerbera',
})

//Metadata
export const metadata: Metadata = {
  title: 'Checkout',
  description: 'Generated by SazzadTanim',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='google-site-verification'
          content='mVhuoyaQb9O-oeJpANj-Ol56TbzLdro7yPcK1epzPfE'
        />
      </head>
      <body
        className={`${inter.className} ${gerbera.variable} mx-auto min-h-screen w-full antialiased sm:bg-bg_color-100 `}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
