import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import Header from "./Header";
import "./globals.css";

// Fonts
const inter = Inter({ subsets: ["latin"] });
const gerbera = localFont({
  src: "./Gerbera-Light.otf",
  variable: "--font-gerbera",
});

//Metadata
export const metadata: Metadata = {
  title: "Checkout page for ecommerce site",
  description: "Generated by SazzadTanim",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${gerbera.variable} bg-bg_color-100 min-h-screen w-full mx-auto `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
